// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact-us": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/categories": {
    params: {};
  };
  "/wizard/*": {
    params: {
      "*": string;
    };
  };
  "/myroute/:myrouteId": {
    params: {
      "myrouteId": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
  "/products/:productId/:productSlug": {
    params: {
      "productId": string;
      "productSlug": string;
    };
  };
  "/products/category/:categorySlug": {
    params: {
      "categorySlug": string;
    };
  };
  "/privacy-policy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/.well-known/appspecific/com.chrome.devtools.json" | "/about" | "/contact-us" | "/products" | "/categories" | "/wizard/*" | "/myroute/:myrouteId" | "/dashboard" | "/dashboard/settings" | "/products/:productId/:productSlug" | "/products/category/:categorySlug" | "/privacy-policy" | "/terms";
  };
  "routes/(public)/home.tsx": {
    id: "routes/(public)/home";
    page: "/";
  };
  "routes/.well-known.appspecific.com.chrome.devtools.json.tsx": {
    id: "routes/.well-known.appspecific.com.chrome.devtools.json";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/(public)/about.tsx": {
    id: "routes/(public)/about";
    page: "/about";
  };
  "routes/(public)/contact.tsx": {
    id: "routes/(public)/contact";
    page: "/contact-us";
  };
  "routes/(public)/products.tsx": {
    id: "routes/(public)/products";
    page: "/products";
  };
  "routes/(public)/categories.tsx": {
    id: "routes/(public)/categories";
    page: "/categories";
  };
  "routes/(componentRouteExample)/wizard.tsx": {
    id: "routes/(componentRouteExample)/wizard";
    page: "/wizard/*";
  };
  "routes/(public)/myRouterWithDefaultParams.tsx": {
    id: "routes/(public)/myRouterWithDefaultParams";
    page: "/myroute/:myrouteId";
  };
  "routes/(private)/dashboard.tsx": {
    id: "routes/(private)/dashboard";
    page: "/dashboard" | "/dashboard/settings";
  };
  "routes/(private)/settings.tsx": {
    id: "routes/(private)/settings";
    page: "/dashboard/settings";
  };
  "routes/products.$productId.$productSlug.tsx": {
    id: "routes/products.$productId.$productSlug";
    page: "/products/:productId/:productSlug";
  };
  "routes/products.category.$categorySlug.tsx": {
    id: "routes/products.category.$categorySlug";
    page: "/products/category/:categorySlug";
  };
  "routes/privacy-policy.tsx": {
    id: "routes/privacy-policy";
    page: "/privacy-policy";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/(public)/home": typeof import("./app/routes/(public)/home.tsx");
  "routes/.well-known.appspecific.com.chrome.devtools.json": typeof import("./app/routes/.well-known.appspecific.com.chrome.devtools.json.tsx");
  "routes/(public)/about": typeof import("./app/routes/(public)/about.tsx");
  "routes/(public)/contact": typeof import("./app/routes/(public)/contact.tsx");
  "routes/(public)/products": typeof import("./app/routes/(public)/products.tsx");
  "routes/(public)/categories": typeof import("./app/routes/(public)/categories.tsx");
  "routes/(componentRouteExample)/wizard": typeof import("./app/routes/(componentRouteExample)/wizard.tsx");
  "routes/(public)/myRouterWithDefaultParams": typeof import("./app/routes/(public)/myRouterWithDefaultParams.tsx");
  "routes/(private)/dashboard": typeof import("./app/routes/(private)/dashboard.tsx");
  "routes/(private)/settings": typeof import("./app/routes/(private)/settings.tsx");
  "routes/products.$productId.$productSlug": typeof import("./app/routes/products.$productId.$productSlug.tsx");
  "routes/products.category.$categorySlug": typeof import("./app/routes/products.category.$categorySlug.tsx");
  "routes/privacy-policy": typeof import("./app/routes/privacy-policy.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
};